# -*- coding: utf-8 -*-
"""data_acquisition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFO7l7hs4G6TU5FcXGRFb1a1g5X1nNpE

##Carga de datos / data_acquisition
"""

import pandas as pd
import csv
from google.colab import drive
drive.mount('/content/drive')

ruta_archivo= '/content/drive/MyDrive/UNAL_Cobros_I.csv'

pd= pd.read_csv(ruta_archivo, sep=';')

pd.head(10)